### PR TITLE
Feature/google autovalue

### PR DESCRIPTION
**Pull request by Ollitod**
Changed implementation of domain models to Google AutoValue and adjusted code in all places

### CODE REVIEW

**Comment by cchet** [comment]
@Ollitod 

Here the results of my review:

**Delete dead code of Employee, dead code is never needed**

**Organise your import, some in UserServiceImpl are not used anymore** 

**Can produce NPE, use Optional.ofNullable(user.role).orElse(null)**
```
UserResourceTest.login_withIdToken_returnsLoggedUser
-> .body("role", equalTo(user.role().name())) 
```

**Stream.filter expects an primitive boolean and the unboxing could cause a NPE**
Make Employee::active primitive boolean, if it is not set then it defaults to false
Builder uses primitive boolean and Employee uses wrapper type Boolean, this is inconsistent
```
EmployeeServiceImpl.getAllActiveEmployees
-> .filter(Employee::active)
```

**Fix this in an own issue, but I found it during this review, therefore I mention it here**
**Get rid of EmployeeTestUtil, because it hides information what values are set on the Employee**
- A test method must be clear and atomic
- Test classes and methods are not meant to be optimised to avoid duplicate code or to abstract things (breaks atomic)
- Someone wants to see and understand 
  - what state is under test (**Given** or **Arrange**),
  - what is executed (and how) (**When** or **Act**) 
  - and how is the result asserted (**Then** or **Assert**)
```
WorkerServiceImplTest.testGetMonthendReportForUser_MitarbeiterInvalid
-> EmployeeTestUtil.createEmployee(0, "NULL"); 
```

Otherwise it looks good.
Fix the issues and I will merge it after @rfischerGep  has approved as well

**Comment by Ollitod** [comment]
After fixing issues and trying to test locally, following exception occurs in UserResourceTest.login_withIdToken_returnsLoggedUser:

JSON path role doesn't match.
Expected: <USER>
  Actual: USER

Am I right that it is not allowed to invoke method name() on user.role() because it can lead to NPE?
Otherwise I don't know how to fix this issue.

**Comment by cchet** [comment]
@Ollitod 

Feel free to commit your change on the feature branch otherwise I cannot help you or you need to add your change to the comment. 
It is no shame if a feature branch build breaks once in a while.
The broken build would illustrate what has failed and the other collaborators could help you, but no its only on your local machine.

 Optional.ofNullable(user.role).orElse(null).name() // Never just copy paste, always question the recommendation because I am sure you left the .name() out because I did :)

**Comment by Ollitod** [comment]
I will do that in the future, i just thought the changes should better not be pushed until it‘s very unlikely that the build fails. I thought about your code and tried to invoke the method .name(), the reason why i didn‘t write it in the end was that IntelliJ warned me again that the method call could cause NPE (like it did before), and I thought that this warning should be avoided. But what if the Role is null? But wouldn’t Optional.ofNullable(user.role()).orElse(null) return null again if user.role() == null? If so, then the invocation of .name() would result in NPE, wouldn‘t it?

**Comment by cchet** [comment]
@Ollitod 

Sorry, should be like this: 

```
Optional.ofNullable(user.role())
              .map(Role::name)               // Only invoked if role is not null, which will return the result of the Method Reference invocation
              .orElse(null)                        // Only invoked if role is null, which will return null
```

**Comment by Ollitod** [comment]
Yeah that makes sense, I will fix it tomorrow in the morning. Thank you.

**Pull request merged**
